# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class DecentAuthorityKey(p.MessageType):

    def __init__(
        self,
        key: bytes = None,
        weight: int = None,
    ) -> None:
        self.key = key
        self.weight = weight

    @classmethod
    def get_fields(cls):
        return {
            1: ('key', p.BytesType, 0),
            3: ('weight', p.UVarintType, 0),
        }
