# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .DecentAuthority import DecentAuthority


class DecentOperationCreateAccount(p.MessageType):

    def __init__(
        self,
        creator: int = None,
        name: int = None,
        owner: DecentAuthority = None,
        active: DecentAuthority = None,
    ) -> None:
        self.creator = creator
        self.name = name
        self.owner = owner
        self.active = active

    @classmethod
    def get_fields(cls):
        return {
            1: ('creator', p.UVarintType, 0),
            2: ('name', p.UVarintType, 0),
            3: ('owner', DecentAuthority, 0),
            4: ('active', DecentAuthority, 0),
        }
