# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class DecentMemo(p.MessageType):

    def __init__(
        self,
        sender_pub_key: bytes = None,
        receiver_pub_key: bytes = None,
        nonce: int = None,
        message: bytes = None,
    ) -> None:
        self.sender_pub_key = sender_pub_key
        self.receiver_pub_key = receiver_pub_key
        self.nonce = nonce
        self.message = message

    @classmethod
    def get_fields(cls):
        return {
            1: ('sender_pub_key', p.BytesType, 0),
            2: ('receiver_pub_key', p.BytesType, 0),
            3: ('nonce', p.UVarintType, 0),
            4: ('message', p.BytesType, 0),
        }
