# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class DecentSignedTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 655

    def __init__(
        self,
        signature: str = None,
    ) -> None:
        self.signature = signature

    @classmethod
    def get_fields(cls):
        return {
            1: ('signature', p.UnicodeType, 0),
        }
