# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .DecentAuthority import DecentAuthority


class DecentOperationUpdateAccount(p.MessageType):

    def __init__(
        self,
        account: str = None,
        permission: int = None,
        parent: int = None,
        auth: DecentAuthority = None,
    ) -> None:
        self.account = account
        self.permission = permission
        self.parent = parent
        self.auth = auth

    @classmethod
    def get_fields(cls):
        return {
            1: ('account', p.UnicodeType, 0),
            2: ('permission', p.UVarintType, 0),
            3: ('parent', p.UVarintType, 0),
            4: ('auth', DecentAuthority, 0),
        }
