# Automatically generated by pb2py
# fmt: off
import protobuf as p


class DecentAsset(p.MessageType):

    def __init__(
        self,
        amount: int = None,
        id: int = None,
    ) -> None:
        self.amount = amount
        self.id = id

    @classmethod
    def get_fields(cls):
        return {
            1: ('amount', p.SVarintType, 0),
            2: ('id', p.UVarintType, 0),
        }
