# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .DecentAccountId import DecentAccountId


class DecentAuthorityAccount(p.MessageType):

    def __init__(
        self,
        account: DecentAccountId = None,
        weight: int = None,
    ) -> None:
        self.account = account
        self.weight = weight

    @classmethod
    def get_fields(cls):
        return {
            1: ('account', DecentAccountId, 0),
            2: ('weight', p.UVarintType, 0),
        }
