# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .DecentTxHeader import DecentTxHeader

if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class DecentSignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 652

    def __init__(
        self,
        address_n: List[int] = None,
        chain_id: bytes = None,
        header: DecentTxHeader = None,
        num_operations: int = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.chain_id = chain_id
        self.header = header
        self.num_operations = num_operations

    @classmethod
    def get_fields(cls):
        return {
            1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
            2: ('chain_id', p.BytesType, 0),
            3: ('header', DecentTxHeader, 0),
            4: ('num_operations', p.UVarintType, 0),
        }
