# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .DecentAccountId import DecentAccountId
from .DecentAccountOptions import DecentAccountOptions
from .DecentAsset import DecentAsset
from .DecentAuthority import DecentAuthority


class DecentOperationAccountUpdate(p.MessageType):

    def __init__(
        self,
        fee: DecentAsset = None,
        account: DecentAccountId = None,
        owner: DecentAuthority = None,
        active: DecentAuthority = None,
        new_options: DecentAccountOptions = None,
    ) -> None:
        self.fee = fee
        self.account = account
        self.owner = owner
        self.active = active
        self.new_options = new_options

    @classmethod
    def get_fields(cls):
        return {
            1: ('fee', DecentAsset, 0),
            2: ('account', DecentAccountId, 0),
            3: ('owner', DecentAuthority, 0),
            4: ('active', DecentAuthority, 0),
            5: ('new_options', DecentAccountOptions, 0),
        }
