# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .DecentAccountId import DecentAccountId
from .DecentAccountOptions import DecentAccountOptions
from .DecentAsset import DecentAsset
from .DecentAuthority import DecentAuthority


class DecentOperationAccountCreate(p.MessageType):

    def __init__(
        self,
        fee: DecentAsset = None,
        registrar: DecentAccountId = None,
        name: str = None,
        owner: DecentAuthority = None,
        active: DecentAuthority = None,
        options: DecentAccountOptions = None,
    ) -> None:
        self.fee = fee
        self.registrar = registrar
        self.name = name
        self.owner = owner
        self.active = active
        self.options = options

    @classmethod
    def get_fields(cls):
        return {
            1: ('fee', DecentAsset, 0),
            2: ('registrar', DecentAccountId, 0),
            3: ('name', p.UnicodeType, 0),
            4: ('owner', DecentAuthority, 0),
            5: ('active', DecentAuthority, 0),
            6: ('options', DecentAccountOptions, 0),
        }
